name: Building recovery

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'omni'
      LIBRARY_URL:
        description: 'LIBRARY_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'
      LIBRARY_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        default: 'twrp-9.0'
      DEVICE_URL:
        description: 'DEVICE_URL'
        required: true
        default: 'https://github.com/shitianshiwa/twrp_device_xiaomi_redmi9a'
      DEVICE_BRANCH:
        description: 'DEVICE_BRANCH'
        required: true
        default: 'twrp-9.0'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/dandelion'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'dandelion'
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5


env:
  MANIFEST: ${{ github.event.inputs.LIBRARY_URL }}
  #https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
  DEVICE:   ${{ github.event.inputs.DEVICE_NAME }}
  DT_LINK: ${{ github.event.inputs.DEVICE_URL }}
  #https://github.com/senpaimaster05/twrp_device_xiaomi_dandelion
  DT_PATH:  ${{ github.event.inputs.DEVICE_PATH }}
  TARGET: recoveryimage
  TZ: Asia/China
  MF_PATH: ${{ github.event.inputs.LIBRARY_BRANCH }}
  BRANd: ${{ github.event.inputs.LIBRARY_NAME }}
jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: linux-amd64

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
              echo " ===+++ Setting up Build Environment +++==="
              sudo apt install openssh-server -y
              sudo apt update --fix-missing
              sudo apt install openssh-server -y
              echo " ===+++ Sync OrangeFox +++==="
              mkdir work 
              cd work
              git clone $MANIFEST $MF_PATH
              #./get_fox_10.sh ~/fox_10.0
              #cd ~/fox_10.0
              git clone $DT_LINK $DT_PATH
              echo " ====+++ Building OrangeFox +++==="
              . build/envsetup.sh
              export ALLOW_MISSING_DEPENDENCIES=true
              #export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
              #export LC_ALL="C"
              lunch ${BRANd}_${DEVICE}-eng && mka recoveryimage
             
       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: TWRP_11.0
          name: TEST
          files: | 
            work/out/target/product/ $DEVICE /recovery.img
